### ISSUE TITLE
Vastaanotetuille kausijulkaisuniteille oma tulostusjono tarratulostustyökaluun

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/koha-plugin-visual-label-tool#1]
### Kehitysehdotukseni

Tiedot Redmine-tiketistä https://tiketti.koha-suomi.fi/issues/3985
Luotu: 07/05/2019

Niteiden muokkaus näytöllä Lisää tulostuslistaan -valintamahdollisuus info ja/tai selkätarran tulostusta varten.

---

Anneli Österman
Asiantuntijaryhmän 15.3.2023 päätös: Toteutetaan jos mahdollista saman tyylisesti kuin Tulostusjonoon-linkki/nappula on lisätty niteiden muokkaukseen.

**Comment by ghost** [comment]
serials-collection.pl -sivulleko tämä tulostusnappi halutaan vai minne? Ei taida pelkällä JavaScriptillä onnistua eikä muutenkaan ihan ongelmattomasti kun tuolta ei pääse yksittäisiin niteisiin käsiksi ja tarratulostustyökalu tarvitsee joko itemnumberin tai barcoden.

**Comment by Kati-Helle** [comment]
Kyllä vain, serials-collection.pl-sivulle. Tarratulostusta varten ei tarvitsisi mennä niteiden muokkaukseen
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b2968bd5-660a-4070-a437-863bbb042181)

Onkohan sama haaste serials-edit.pl -sivulla, jossa lehtinumero on jo vastaanotettuna? 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/6dd59499-0630-4adf-9962-ae1dee512fc1)

**Comment by ghost** [comment]
On sama haaste, molemmilla sivuilla kun on lehtinumeroita eikä yksittäisiä niteitä. Koodimuutoksilla tarratulostustyökaluun saattaisi onnistua ja serials-collection-sivulta numeroita saisi kyllä mukavasti ruksittua tulostettaviksi. Mutta tuleekohan tässä paljonkin poikkeustilanteita joissa lehtinumero on olemassa mutta ei yhtään nidettä sille tai samaa lehtinumeroa on useammassa kirjastossa eri viivakoodilla tai muuta vastaavaa?

**Comment by Kati-Helle** [comment]
Samaa lehtinumeroa useammassa kirjastossa -tapauksia on erittäin todennäköisesti viikottain. Tämä ei ymmärtääkseni olisi kuitenkaan ongelma. 
Koha-Suomen Tarratulostustyökalu-ohjeessa mainitaan näin:
Valitse lista -valikon Oma tulostusjono -valinnalla saa listan kaikista niteistä, jotka käyttäjä on vienyt nidenäytöllä tulostusjonoon. Ks. ohje alla. Tänään vastaanotetut -valinta tuo listan kaikista kyseisenä päivänä kirjautusmiskirjastossa vastaanotetuista niteistä. Itse tulostetut -valinta tuo listan kirjautuneen käyttäjän aiemmin tulostamista niteistä.

Tekstin nappasin täältä: https://koha-suomi.fi/dokumentaatio/tyokalut/#1294-tarratulostusty%C3%B6kalu

Kausijulkaisutilausten vastaanotossa haettaneen aina tietyn kirjaston lehtitilaus. (Kirjaston, jossa tilauksen vastaanottaja työskentelee.)

**Comment by ghost** [comment]
Tänään vastaanotetut -listalta pitäisi löytyä oikeat niteet automaattisesti ilman tulostusnappiakin mutta toimiiko tuo oikein, omalla testikoneellani lista pysyy tyhjänä? Lehtinumeron serialid:n sekä kirjastoyksikön perusteella saa kyllä haettua tietokannasta sopivan niteen (jos sellainen vain on olemassa) mutta vaatii tosiaan muutoksia tarratulostustyökaluun.

**Comment by AnneliO** [comment]
Tänään vastaanotetut -listalle tulee mielestäni vain Hankinnassa vastaanotetut niteet, ei kausijulkaisu-osiossa vastaanotetut.

**Comment by AnneliO** [comment]
Kausijulkaisunumeroa vastaanotettaessahan avautuu tällainen näkymä:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/c1df8015-abe7-4f1d-a0bd-198b5ff0ac3c)

Saako tuosta poimittua viivakoodin, jos sen siihen ensin generoi klikkaamalla kolmea pistettä?

**Comment by ghost** [comment]
> Saako tuosta poimittua viivakoodin, jos sen siihen ensin generoi klikkaamalla kolmea pistettä?

Saisihan siitä mutta ei taida kauheasti helpottaa tilannetta jos tulostusnappi olisi vain yhdelle niteelle?

**Comment by AnneliO** [comment]
Yhdelle niteelle mie ainakin sen ole ajatellut tulevan. Eli minusta prosessi menisi näin:

1. Haetaan vastaanotettavan lehden tiedot Kausijulkaisut-osiossa.
2. Otetaan vastaan seuraava numero.
3. Valitaan Tila-valikosta _Saapunut_, jolloin avautuu niteen tiedot muokattavaksi.
4. Generoidaan niteelle viivakoodi.
5. Klikataan (esim.) Tallenna-painikkeen vieressä olevaa _Lisää tulostuslistalle_ -painiketta.
6. Klikataan _Tallenna_-painiketta.

Eli tämän tyylisesti:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/84488b3e-2535-45f3-b17d-37247472a6c4)

Jos joku muu oli ajatellut prosessin toisenlaiseksi, niin laitatko tähän kuvauksen? :)

**Comment by Kati-Helle** [comment]
> > Saako tuosta poimittua viivakoodin, jos sen siihen ensin generoi klikkaamalla kolmea pistettä?
> 
> Saisihan siitä mutta ei taida kauheasti helpottaa tilannetta jos tulostusnappi olisi vain yhdelle niteelle?

Helpottaisi tuo :) Yhteen kirjastoon lienee pääsääntöisesti tilattu yksi lehtivuosikerta lehteä kohden, jolloin kerralla vastaanotettavia tietyn lehden numeroita on yksi.

**Comment by Kati-Helle** [comment]
Annelin ehdotus hyvä, kätevä, ja lehtien vastaanottajien työtä helpottava.

**Comment by Kati-Helle** [comment]
Testasin Helle-testissä Kausijulkaisun vastaanottoa.

Vastaanotin lehtinumeron, jonka niteen viivakoodi näkyy tässä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d182eb19-576f-4751-b454-d8ad1b105e58)

Tarratulostuksessa nide näkyy listauksessa Tänään vastaanotettu (kuten toinenkin äsken vastaanottamani lehtinide)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ae83aa85-e157-4a6f-b070-93aa9fd4f5f5)

Sen sijaan tarratulostuksen Oma tulostusjono -listauksesta nide puuttuu
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/3ea10838-a42b-4d1b-9482-5c83c71d069b)

**Comment by AnneliO** [comment]
Haa, olen varmaankin aina testannut vastaanottoa niin, että olen ottanut vastaan jonkin muun kirjaston lehtiä kuin mihin olen kirjautuneena. Tuohan on hyvä, että ne menee vastaanotettujen listalle. Tosin, niitä voi olla kyllä sieltä vaikea bongata, jos muutakin aineistoa on otettu päivän aikana paljon vastaan juuri siinä toimipisteessä. Sen vuoksi tuo yksittäisen vastaanotettavan niteen lisääminen tulostuslistalle on hyvä vaihtoehto.

Testasin vielä niin, että tuossa vastaanotettaessa laitoin _Lisättäviä kopioita niteestä_ -kohtaan kakkosen, niin kumpikin nide tuli näkyville Tänään vastaanotettujen listalle.

**Comment by ghost** [comment]
Nidettä ei tosin voi viedä tulostusjonoon ennen kuin se on luotu, siinä mielessä Annelin ehdotus tulostusnapin paikaksi on myös hiukan ongelmallinen.

**Comment by AnneliO** [comment]
No se on sitten kyllä ongelma.

Sitten taitaa olla ainoa paikka tämä [Numerohistoria](https://outi-test.koha-suomi.fi/cgi-bin/koha/serials/serials-collection.pl?subscriptionid=19545)-sivu, jossa voi valita tietyn numeron. Tuossa ei tosin näy, että nidettä voi olla kaksi tai useampi vastaanotettuna. Mutta toisaalta, haittaako se, että silloin menisi kumpikin/kaikki nide/niteet tulostuslistalle? Jos niitä on tullut kaksi, niin eikö kummallekin haluta silloin tarra?

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/6eef237a-ca5e-4941-9f8a-f6a04046b918)

**Comment by ghost** [comment]
Tuolle sivulle sitä alunperin ajattelin mutta sieltä puuttui se itemnumber, tarratulostustyökalua pitäisi muuttaa niin että se osaisi hakea oikeat niteet serialid:n perusteella.

**Comment by AnneliO** [comment]
Ehdotan, että keskustellaan tästä sekä Koha-Suomen palaverissa torstaina että tarvittaessa vielä pääkäyttäjäpalaverissa vkolla 38.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 14.9.2023: Ehdotetaan pääkäyttäjille, että lisätään kausijulkaisuille oma kirjastokohtainen tulostusjono, johon menee tänään vastaanotetut kausijulkaisuniteet.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 20.9.2023: Koha-Suomen palaverin ehdottama oma kirjastokohtainen tulostujono on riittävä. Voidaan mennä sillä.

**Comment by ghost** [comment]
Testeille lisätty erillinen tulostusjono tänään vastaanotetuille kausijulkaisuille. "Tänään vastaanotetut"-listalla edelleen kaikki aineistotyypit, myös kausijulkaisut.

**Comment by Kati-Helle** [comment]
Toimii Helle-testissä testatessani.

Tarratulostustyökalussa on nyt uusi lista Tänään vastaanotetut kausijulkaisut
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ce8016b9-6e13-4e8e-a1e5-5b43b9a441a1)

Vastaanotin kausijulkaisuniteen
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ffe7a440-3472-4072-8f0d-0258e3149309)

Nide on tarratulostustyökalun Tänään vastaanotetut kausijulkaisut -listalla
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d38e1633-c4cd-40fe-92db-166a93918a4d)

Tarra on myös Tänään vastaanotetut -listalla
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/961d8dd2-616f-4076-97a5-f2f6ba7cb348)

Tarra tulostettuna tarratulostustyökalussa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9ecec788-ed83-453e-8285-605c80f617e3)

**Comment by Kati-Helle** [comment]
Tarralle tulostuu myös tarrapohjaan määritelty hyllypaikkatieto

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/84849e1e-e895-4bcc-a2b3-c5a1e035061c)

**Comment by ajrajala** [comment]
Näyttäisi toimivan kuvatulla tavalla myös Vaski-testissä. Listalle tuli kaikki ko. käyttäjän kirjastolle tänään vastaanotetut lehdet.

**Comment by Kati-Helle** [comment]
Tämä on nyt myös tuotannossa.

(Koha-päivitys 24.10.2023)
