### ISSUE TITLE
Tarrapohjalle kokoelma-tieto selkokielisenä (description)

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/koha-plugin-visual-label-tool#2]
### Kehitysehdotukseni

Siirretty [Redminestä tiketistä 3626](https://tiketti.koha-suomi.fi/issues/3626), [RedGrave 3626](https://github.com/KohaSuomi/RedGrave/blob/main/Kehitysehdotukset/2018/%233626%20Tarrapohjalle%20kokoelma-tieto%20selkokielisen%C3%A4%20(description).md).

Saisiko tarrapohjalle laitettua kokoelma-tiedon (ccode) selkokielisenä (description)? Oulussa haluttaisiin lisätä kokoelma-tieto tarralle, mutta sinne saa tällä hetkellä vain kokoelmakoodin tunnuksen, joka ei ole hyvä vaihtoehto.

---

Koha-Suomen asiantuntijaryhmä 30.10.2023: Toteutetaan niin, että tarralle saa edelleen myös kokoelmakoodin tunnuksen.

**Comment by atarnus** [comment]
Olen löytänyt tähän jo ratkaisun, mutta nämä branchin teot ei onnistu vielä soolona, jatkan kun saan kaverin avuksi :)

VisualLabelTool/Modules/Fields.pm -tiedostoon lisätään vain seuraavat tiedot:

sub getItem { -kohdan alle:
`'items.collection',`

ja sub customField { -kohdan alle:
`$data->{items}->{collection} = Koha::AuthorisedValues->search({ category => 'CCODE', authorised_value => $data->{items}->{ccode} })->next ? Koha::AuthorisedValues->search({ category => 'CCODE', authorised_value => $data->{items}->{ccode} })->next->lib : $data->{items}->{ccode};`

Koodissa oli valmiina items.sub_locationista johdettu kuvailtu arvo 'subloc', jota voi käyttää myös ccodelle.

Voidaan käyttää muutakin arvoa kuin items.collection näkymään tarratulostimen kentissä.

![image](https://github.com/KohaSuomi/koha-plugin-visual-label-tool/assets/63994411/7b38d134-fb27-48ce-aac7-abf3420eb943)
![image](https://github.com/KohaSuomi/koha-plugin-visual-label-tool/assets/63994411/10c837ef-75db-4549-911e-e9bec1f79a0d)

**Comment by atarnus** [comment]
Viety testeille.

**Comment by MikkoLiimatainen** [comment]
Testasin vaihtamalla custom kenttään, jossa on muutakin tietoa, items.ccoden tilalle items.collection ja kaikki käytössä olevat kokoelmakoodit tulivat tarralle selkokielisinä. Toimii siis hienosti.

**Comment by pknuuti** [comment]
Toimii Vaaran testilläkin kuten pitää, kun vaihtaa items.ccoden tilalle items.collection. Toinen juttu on se, että jos otetaan tuo käyttöön, pitää tarran muotoilua muokata, pitkät kokoelmakoodit aiheuttaa päällekäisyyttä tarrapohjalla. Se on meidän päätettävä, kummin tehdään.

**Comment by ReettaSiili** [comment]
Items.collection toimii moitteitta myös Siilissä. Asettelu vaatii tosiaan muokkausta kuten Päivi kommentoi, pitkiä ovat kuvailut meilläkin.

**Comment by AnneliO** [comment]
Kokoelmakoodin selkokielinen vaihtoehto lisätty [liitännäisen dokumentaatioon](https://github.com/KohaSuomi/koha-plugin-visual-label-tool/wiki/Tarratulostusty%C3%B6kalu).

**Comment by AnneliO** [comment]
Muutos tuotannossa, suljen tiketin.
