### ISSUE TITLE
Kyyti: tarratulostuksen Itse tulostetut -listalla liikaa niteitä

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/koha-plugin-visual-label-tool#3]
### Mikä vikana?

Eräällä paljon tarroja tulostavalle on tarratulostustyökalun Itse tulostetut -listaan kertynyt niin paljon niteitä, että selain hyytyi niitä ladatessa. Niiden poistaminen yksittäin on valtava työ, jos sen edes saa tehtyä, kun selainkin tosiaan hyytyi. Tästä heräsi kysymyksiä. Minne ne tallentuvat? Voiko niitä kertyä niin paljon että alkavat viedä jo liikaa tilaa? Voiko niitä poistaa massana (joko työkaluun tehtävällä toiminnolla tai kehittäjän tekemänä poistona)?

Vastauksia Matrixissa:
- Menevät tauluun: koha_plugin_fi_kohasuomi_visuallabeltool_print_queue
- Kyytissä rivejä taulussa 113 194
- Häviävät jonkin aikarajan perusteella Itse tulostetut -listasta

Tiedostokoko ei siis liene ongelma, mutta yksittäiselle käyttäjälle voi tulostettuja niteitä kertyä niin paljon, että selain ei sitä kestä. Mikähän on tarkka aikaraja? Olisikohan sitä syytä pienentää?

### Mitä pitäisi tapahtua

Tarratulostustyökalun Itse tulostetut -listalle ei pitäisi kertyä niin paljon niteitä, ettei selain saisi niitä ladatuiksi.

**Comment by lmstrand** [comment]
Voidaan poistaa ensihätään käsinkin, jos annatte asiakas-id:n ja päivämäärän, jota vanhemmat poistetaan itse tulostettujen listalta. Voisihan työkaluun lisätä toiminnon niiden siivoamiseen.

**Comment by Tuomas-Kyyti** [comment]
Kyseinen työntekijä on tänään pois, joten palaan asiaan ensi viikolla. Mutta katsoin tuota taulua ja kyseisellä henkilöllä on siellä yli 25 000 riviä heinäkuusta 2022 alkaen, että jos nuo kaikki tosiaan tulevat myös käyttöliittymässä esiin, niin ei ihme jos on hidas. Ei siis vaikuta siltä, että tuolta taulusta olisi ainakaan mitään poistunut muutamaan vuoteen.

**Comment by johannaraisa** [comment]
Voidaan poistella nuo ylimääräiset ja tekisin tuohon sellaisen, että sieltä poistetaan käyttäjältä sivulatauksen yhteydessä pari kuukautta vanhempia tulostuksia.

**Comment by johannaraisa** [comment]
Poistin kaikista kimpoista paria kuukautta vanhemmat tulostetut niteet tulostusjono-taulusta. @atarnus tekee ominaisuuden, että niitä poistellaan jatkossa aktiivisesti.

**Comment by Tuomas-Kyyti** [comment]
> Poistin kaikista kimpoista paria kuukautta vanhemmat tulostetut niteet tulostusjono-taulusta. @atarnus tekee ominaisuuden, että niitä poistellaan jatkossa aktiivisesti.

Tämä tiketti on meidän puolesta ok. Sulkeeko @atarnus tämän sitten kun tuo ominaisuus on valmis.

**Comment by atarnus** [comment]
Vielä voisin tiedustella, että laitetaanko muuta putsausta kuin tuo käyttäjän 2kk vanhemmat tulostetut? Vai haittaako tuo jos sinne jotain ikivanhoja jää sitten roikkumaan, ei niitä varmaan ihan kasapäin kuitenkaan jää.

**Comment by Tuomas-Kyyti** [comment]
> Vielä voisin tiedustella, että laitetaanko muuta putsausta kuin tuo käyttäjän 2kk vanhemmat tulostetut? Vai haittaako tuo jos sinne jotain ikivanhoja jää sitten roikkumaan, ei niitä varmaan ihan kasapäin kuitenkaan jää.

Ei varmasti haittaa.

**Comment by atarnus** [comment]
Toiminnallisuus on nyt testeillä. Työkalun etusivua ladatessa poistuu automaattisesti print_queue-taulusta yli 9 viikkoa vanhat jo tulostetut niteet. Tärkeintä olisi kait vähän testata ettei mikään mennyt rikki :)

(Jos olet kovin sukkela valitsemaan pudotusvalikosta tulostetut, niin ne voivat vielä ehtiä mukaan sivulle ennen kuin poisto on suoritettu. Niiden tieto näyttäisi oman pienen testauksen mukaan kuitenkin päätyvän vielä ihan oikein tulostukseen asti, ja jos listan lataa uudestaan, niin niteet ovat sitten poistuneet.)

**Comment by MikkoLiimatainen** [comment]
Vaikuttaisi toimivalta. Helmikuulta olleet tulostukset poistuivat jonosta, kun avasin työkalun. Juuri tehdyt uudet eivät poistu.

**Comment by Tuomas-Kyyti** [comment]
Kyytin testikannassa on niin vähän ja niin harvan tekemiä tarratulostuksia, että en voi sanoa mitään varmaa toimivuudesta. Mutta itse tarratulostus ainakin toimii ja vanhimmat tulostukset näyttävät olevan huhtikuulta.

**Comment by Tuomas-Kyyti** [comment]
Tämä tuotannossa ok.
