### ISSUE TITLE
Niteiden lisääminen tulostusjonoon pluginin mukana tulevalla javascript-rimpsulla

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-visual-label-tool#4]
/// Niteiden lisäys tarratulostusjonoon. Ilman näitä niteitä ei saa vietyä niteiden muokkauksesta ja perustiedot-näytöltä omaan tulostusjonoon. ///

Pluginin tarvitsemat kaksi rimpsua on nyt lisätty pluginiin itseensä siellä ylläpidettäviksi. Toiminta pitäisi testata.

Testaus:

Poista rimpsut " Niteiden lisäys tarratulostusjonoon" ja "Niteiden lisätys tarratulostustyökaluun perustiedot-näytöltä" intranetuserJS-asetuksesta.

Tarkista, että tarratulostusjonoon lisääminen onnistuu edelleen molemmista paikoista.

**Comment by lmstrand** [comment]
![image](https://github.com/user-attachments/assets/b4176a44-d494-4d47-b8f7-e2fb709905dd)

**Comment by pknuuti** [comment]
Missä tämän pitäisi toimia? Tuotannossa ei tietenkään voi testata, mutta ei toimi nextillä eikä testillä Vaaran kannoissa. Nextillä näyttää liitännäisen päivityspäivä eiliseltä eli siellä kaiketi pitäisi toimia, mutta ei toimi.

**Comment by lmstrand** [comment]
Ok kiitos. Jossakin on sitten ongelma. Tutkin asiaa.

**Comment by lmstrand** [comment]
Niin ja tämä tosiaan nexteillä testattavissa.

**Comment by AnneliO** [comment]
Kommentoi tikettiä, kun rimpsut on poistettu IntranetUserJS-asetuksesta ja toiminto toimii liitännäisen perusteella:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by lmstrand** [comment]
Itse javascript-skriptitiedosto oli jäänyt kyydistä. Nyt pitäisi toimia tulostusjonoon lisääminen pluginin mukana tulevalla js-skriptillä.

**Comment by pknuuti** [comment]
No nyt toimii Vaaran nextillä.

**Comment by pirliis** [comment]
Testattu OUTIn nextillä, toimii.

**Comment by MikkoLiimatainen** [comment]
Lisääminen toimii, mutta js-rimpsussa mukana ollut Tulosta tarra -valinnan piilotus niteen muokkaussivulta $(".print_label").hide(); ei ilmeisesti ole tässä mukana? Tuleeko tämä mukaan, vai tehdäänkö piilotus css:llä?

**Comment by lmstrand** [comment]
> Lisääminen toimii, mutta js-rimpsussa mukana ollut Tulosta tarra -valinnan piilotus niteen muokkaussivulta $(".print_label").hide(); ei ilmeisesti ole tässä mukana? Tuleeko tämä mukaan, vai tehdäänkö piilotus css:llä?

Lisäsin piilotuksen pluginin versioon Vaskin tuotannossa olleen rimpsun mukaisesti. On päivitetty nexteille.

**Comment by MikkoLiimatainen** [comment]
Nyt on tulosta tarra -valinta piilossa ja niteiden lisäämiset toimivat edelleen.

**Comment by LeenaKinnunen** [comment]
Lapissa plugari käytössä ja toimii tulostukseen vienti molemmilta näytöiltä.

**Comment by Kati-Helle** [comment]
Helle-nextissä käytössä ja toimii.

**Comment by Tuomas-Kyyti** [comment]
Kyytin nextillä kunnossa ja toimii

**Comment by LastuJanneS** [comment]
Lastun next testattu ja toimii

**Comment by ElinaUotila** [comment]
Kirkesin nextillä testattu ja toimii

**Comment by Hanna-Lumme** [comment]
Lumpeissa lisätty nextille ja toimii.

**Comment by ReettaSiili** [comment]
Siilissä toimii.

**Comment by AnneliO** [comment]
Kaikki kimpat kuitanneet, joten suljen tiketin. :)
